[package]
name = "pedersen_py_backend"
version = "0.1.0"
edition = "2024"

[lib]
name = "pedersen_py_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
